import { Lesson, Quiz, User, Announcement, StudentProgress } from '../types/models';

export const dummyUsers: User[] = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah@lms.com',
    role: 'teacher',
  },
  {
    id: '2',
    name: 'John Smith',
    email: 'john@student.com',
    role: 'student',
    grade: 10,
  },
  {
    id: '3',
    name: 'Emma Wilson',
    email: 'emma@student.com',
    role: 'student',
    grade: 9,
  },
];

export const dummyLessons: Lesson[] = [
  {
    id: '1',
    title: 'Introduction to Algebra',
    description: 'Learn the fundamentals of algebraic expressions and equations',
    grade: 10,
    curriculum: 'Cambridge',
    topic: 'Algebra',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdfUrl: '/sample-lesson.pdf',
    notes: '# Introduction to Algebra\n\nAlgebra is a branch of mathematics that uses symbols and letters to represent numbers and quantities in formulas and equations.\n\n## Key Concepts\n\n- **Variables**: Letters that represent unknown values\n- **Constants**: Fixed values\n- **Expressions**: Combinations of variables and constants\n- **Equations**: Mathematical statements with equality',
    createdAt: '2024-01-15',
    teacherId: '1',
  },
  {
    id: '2',
    title: 'Quadratic Equations',
    description: 'Understanding quadratic equations and their solutions',
    grade: 11,
    curriculum: 'Edexcel',
    topic: 'Algebra',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdfUrl: '/quadratic-equations.pdf',
    notes: '# Quadratic Equations\n\nA quadratic equation is a polynomial equation of degree 2.\n\n## Standard Form\n\nax² + bx + c = 0\n\n## Methods of Solving\n\n1. Factoring\n2. Quadratic Formula\n3. Completing the Square',
    createdAt: '2024-01-20',
    teacherId: '1',
  },
  {
    id: '3',
    title: 'Trigonometry Basics',
    description: 'Introduction to trigonometric functions and identities',
    grade: 10,
    curriculum: 'Local',
    topic: 'Trigonometry',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdfUrl: '/trigonometry-basics.pdf',
    notes: '# Trigonometry Basics\n\nTrigonometry deals with relationships between angles and sides of triangles.\n\n## Main Functions\n\n- **Sine (sin)**: Opposite/Hypotenuse\n- **Cosine (cos)**: Adjacent/Hypotenuse\n- **Tangent (tan)**: Opposite/Adjacent',
    createdAt: '2024-01-25',
    teacherId: '1',
  },
  {
    id: '4',
    title: 'Geometry: Circles',
    description: 'Properties and theorems related to circles',
    grade: 9,
    curriculum: 'Cambridge',
    topic: 'Geometry',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdfUrl: '/circles.pdf',
    notes: '# Circles\n\nA circle is a set of all points equidistant from a center point.\n\n## Key Properties\n\n- **Radius**: Distance from center to edge\n- **Diameter**: Twice the radius\n- **Circumference**: 2πr\n- **Area**: πr²',
    createdAt: '2024-02-01',
    teacherId: '1',
  },
  {
    id: '5',
    title: 'Statistics and Probability',
    description: 'Understanding data analysis and probability concepts',
    grade: 8,
    curriculum: 'Edexcel',
    topic: 'Statistics',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdfUrl: '/statistics.pdf',
    notes: '# Statistics and Probability\n\nStatistics involves collecting, analyzing, and interpreting data.\n\n## Key Concepts\n\n- **Mean**: Average of values\n- **Median**: Middle value\n- **Mode**: Most frequent value\n- **Probability**: Likelihood of an event',
    createdAt: '2024-02-05',
    teacherId: '1',
  },
  {
    id: '6',
    title: 'Calculus: Derivatives',
    description: 'Introduction to differential calculus',
    grade: 11,
    curriculum: 'Cambridge',
    topic: 'Calculus',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    pdfUrl: '/derivatives.pdf',
    notes: '# Derivatives\n\nA derivative represents the rate of change of a function.\n\n## Basic Rules\n\n- Power Rule: d/dx(xⁿ) = nxⁿ⁻¹\n- Product Rule: (fg)\' = f\'g + fg\'\n- Quotient Rule: (f/g)\' = (f\'g - fg\')/g²',
    createdAt: '2024-02-10',
    teacherId: '1',
  },
];

export const dummyQuizzes: Quiz[] = [
  {
    id: '1',
    title: 'Algebra Fundamentals Quiz',
    description: 'Test your understanding of basic algebra',
    grade: 10,
    curriculum: 'Cambridge',
    topic: 'Algebra',
    questions: [
      {
        id: 'q1',
        question: 'What is the value of x in the equation 2x + 5 = 13?',
        options: ['3', '4', '5', '6'],
        correctAnswer: 1,
      },
      {
        id: 'q2',
        question: 'Simplify: 3x + 2x - 5x',
        options: ['0', 'x', '5x', '10x'],
        correctAnswer: 0,
      },
      {
        id: 'q3',
        question: 'What is the coefficient of x in 7x + 3?',
        options: ['3', '7', '10', 'x'],
        correctAnswer: 1,
      },
    ],
    createdAt: '2024-01-16',
    teacherId: '1',
  },
  {
    id: '2',
    title: 'Quadratic Equations Quiz',
    description: 'Test your knowledge of quadratic equations',
    grade: 11,
    curriculum: 'Edexcel',
    topic: 'Algebra',
    questions: [
      {
        id: 'q1',
        question: 'What is the solution to x² - 5x + 6 = 0?',
        options: ['x = 2, x = 3', 'x = -2, x = -3', 'x = 1, x = 6', 'x = 0, x = 5'],
        correctAnswer: 0,
      },
      {
        id: 'q2',
        question: 'What is the discriminant of x² + 4x + 4 = 0?',
        options: ['0', '4', '8', '16'],
        correctAnswer: 0,
      },
    ],
    createdAt: '2024-01-21',
    teacherId: '1',
  },
  {
    id: '3',
    title: 'Trigonometry Quiz',
    description: 'Test your trigonometry knowledge',
    grade: 10,
    curriculum: 'Local',
    topic: 'Trigonometry',
    questions: [
      {
        id: 'q1',
        question: 'What is sin(90°)?',
        options: ['0', '0.5', '1', '√2/2'],
        correctAnswer: 2,
      },
      {
        id: 'q2',
        question: 'In a right triangle, if opposite = 3 and hypotenuse = 5, what is sin(θ)?',
        options: ['3/5', '4/5', '3/4', '5/3'],
        correctAnswer: 0,
      },
    ],
    createdAt: '2024-01-26',
    teacherId: '1',
  },
];

export const dummyAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Welcome to O/L Mathematics Class!',
    content: 'Welcome all students to the new academic year. We will be covering topics from Grades 6-11 across Local, Edexcel, and Cambridge curricula.',
    createdAt: '2024-01-10',
    teacherId: '1',
  },
  {
    id: '2',
    title: 'Quiz Schedule Update',
    content: 'The Algebra Fundamentals Quiz will be available from January 20-25. Please complete it before the deadline.',
    createdAt: '2024-01-18',
    teacherId: '1',
  },
  {
    id: '3',
    title: 'New Lesson Available',
    content: 'A new lesson on Quadratic Equations has been uploaded. Please review the materials and complete the associated quiz.',
    createdAt: '2024-01-22',
    teacherId: '1',
  },
];

export const dummyProgress: StudentProgress[] = [
  {
    studentId: '2',
    grade: 10,
    lessonsCompleted: 2,
    totalLessons: 3,
    quizzesCompleted: 1,
    totalQuizzes: 2,
    averageScore: 85,
    rank: 1,
  },
  {
    studentId: '3',
    grade: 9,
    lessonsCompleted: 1,
    totalLessons: 2,
    quizzesCompleted: 0,
    totalQuizzes: 1,
    averageScore: 0,
    rank: 2,
  },
];

